palette = "catppuccin_mocha"

format = """
$directory\
$git_branch\
$git_status\

$fill\

$php\
$nodejs\
$python\
$java\
$ruby\
$golang\
$lua\
$rust\

$cmd_duration\

$line_break\

$sudo\
$character"""

[character]
success_symbol = '[➜](bold green)'
error_symbol = "[➜](bold red)"

[aws]
symbol = "  "
disabled = true

[cmd_duration]
format = "[ $duration]($style) "
disabled = false
style = "yellow"
show_notifications = false
min_time = 5_000
min_time_to_notify = 1000

[directory]
read_only = " 󰌾"
truncation_length = 0
truncate_to_repo = false

[docker_context]
format = "[$symbol$context]($style) "
symbol = " "

[fill]
symbol = " "

[git_branch]
symbol = " "

[git_commit]
tag_symbol = '  '

[golang]
format = "[$symbol($version )]($style)"
symbol = " "

[java]
format = "[$symbol($version )]($style)"
symbol = " "

[lua]
format = "[$symbol($version )]($style)"
symbol = " "

[nodejs]
format = "[$symbol($version )]($style)"
symbol = " "

[php]
format = "[$symbol($version )]($style)"
symbol = " "

[python]
format = "[${symbol}${pyenv_prefix}(${version} )(($virtualenv) )]($style)"
symbol = " "

[ruby]
format = "[$symbol($version )]($style)"
symbol = " "

[rust]
format = "[$symbol($version )]($style)"
symbol = "󱘗 "

[sudo]
style = 'bold green'
format = "[$symbol ]($style)"
symbol = ' '
disabled = false

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"